/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab8;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] arg) {
    	System.out.println("This is a print statement");
    	// Add a comment 
    }
}
